"""Verifiable progress oracle for Pokemon Red.

Every milestone here resolves to a bit somewhere in RAM, so "how far along is
this run" is a memory read rather than a judgement call. The table itself comes
from the *pokered* decomp and is regenerated by ``scripts/gen_milestones.py``
into ``pokemon_agent/data/red_milestones.json``; nothing in this module reaches
the network.

Three kinds of milestone, distinguished by ``Milestone.kind``:

* ``event`` -- a bit in ``wEventFlags`` (0xD747). ``source`` is the pokered
  ``EVENT_`` name and ``ALL_EVENTS`` maps it to its bit index.
* ``badge`` -- a bit in ``wObtainedBadges`` (0xD356). ``source`` is ``badge_bit:N``.
* ``item``  -- a key item present in the bag. ``source`` is ``item_id:N``.

Bit order inside ``wEventFlags`` is little-endian per byte, matching pokered's
``flag_array``: event *i* lives in byte ``i // 8`` at mask ``1 << (i % 8)``. That
is not an assumption. Two independent confirmations:

* ``pokemon_agent/memory/red.py`` already carried ``ADDR_POKEDEX_FLAG = 0xD74B``
  bit 5 and ``ADDR_OAK_PARCEL = 0xD74E`` bit 1, read off a running game years
  before this table existed. EVENT_GOT_POKEDEX parses as bit 37 (byte 4, bit 5)
  and EVENT_GOT_OAKS_PARCEL as bit 57 (byte 7, bit 1). Both land exactly there.
* Sweeping all 3277 save states in ``saves/``: ``wObtainedBadges`` bit 0 (Boulder
  Badge) and EVENT_BEAT_BROCK (bit 119 -> byte 14, mask 0x80) agree in every
  single one, 444 set and the rest clear, zero disagreements. The big-endian
  reading puts EVENT_BEAT_BROCK at byte 14 mask 0x01, which is clear in all 444
  badge-holding states -- so it is not merely unconfirmed, it is refuted.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any, Dict, List, Mapping, Tuple

from pokemon_agent.memory.red import ADDR_EVENT_FLAGS, BADGE_NAMES

DATA_PATH = Path(__file__).resolve().parent / "data" / "red_milestones.json"

#: wEventFlags is NUM_EVENTS = 0xA00 bits wide.
EVENT_FLAG_BYTES = 0xA00 // 8

#: How many trailing ladder entries ``summary()["latest"]`` reports.
LATEST_LIMIT = 5


@dataclass(frozen=True)
class Milestone:
    id: str
    label: str
    kind: str  # "event" | "badge" | "item"
    source: str
    ladder_index: int  # -1 if not on the curated ladder


def _load() -> Tuple[Tuple[Milestone, ...], Mapping[str, int]]:
    document = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    events = {entry["id"]: entry["bit_index"] for entry in document["events"]}
    ladder = tuple(
        Milestone(
            id=entry["id"],
            label=entry["label"],
            kind=entry["kind"],
            source=entry["source"],
            ladder_index=index,
        )
        for index, entry in enumerate(document["ladder"])
    )
    return ladder, MappingProxyType(events)


MILESTONES: Tuple[Milestone, ...]
ALL_EVENTS: Mapping[str, int]
MILESTONES, ALL_EVENTS = _load()

MILESTONES_BY_ID: Mapping[str, Milestone] = MappingProxyType({m.id: m for m in MILESTONES})


def milestone_for_event(event_id: str) -> Milestone:
    """Milestone view of any ``EVENT_`` name, on the ladder or not.

    Off-ladder events get ``ladder_index == -1``: they are still verifiable, they
    just do not move the score.
    """
    known = MILESTONES_BY_ID.get(event_id)
    if known is not None and known.kind == "event":
        return known
    if event_id not in ALL_EVENTS:
        raise KeyError(event_id)
    return Milestone(id=event_id, label=event_id, kind="event", source=event_id, ladder_index=-1)


def _source_number(source: str) -> int:
    return int(source.split(":", 1)[1])


class MilestoneTracker:
    """Reads the curated ladder out of a live game.

    Parameters
    ----------
    reader : PokemonRedReader
        Any :class:`~pokemon_agent.memory.red.RedBlueMemoryReader`.
    """

    def __init__(self, reader: Any) -> None:
        self.reader = reader

    # -- reads --------------------------------------------------------------

    def _event_bits(self) -> List[bool]:
        # read_bits is already LSB-first per byte, which is pokered's flag_array order.
        return self.reader.read_bits(ADDR_EVENT_FLAGS, EVENT_FLAG_BYTES)

    def _badge_bits(self) -> set[int]:
        obtained = set(self.reader.read_flags()["badges"])
        return {bit for bit, name in enumerate(BADGE_NAMES) if name in obtained}

    def _bag_item_ids(self) -> set[int]:
        return {entry["id"] for entry in self.reader.read_bag()}

    # -- public interface ---------------------------------------------------

    def snapshot(self) -> frozenset[str]:
        """Ids of every ladder milestone currently satisfied."""
        bits = self._event_bits()
        badges = self._badge_bits()
        items = self._bag_item_ids()

        reached: List[str] = []
        for milestone in MILESTONES:
            if milestone.kind == "event":
                index = ALL_EVENTS[milestone.source]
                ok = index < len(bits) and bits[index]
            elif milestone.kind == "badge":
                ok = _source_number(milestone.source) in badges
            else:
                ok = _source_number(milestone.source) in items
            if ok:
                reached.append(milestone.id)
        return frozenset(reached)

    def newly_set(self, previous: frozenset[str]) -> Tuple[str, ...]:
        """Milestones reached since *previous*, in ladder order.

        An empty *previous* therefore yields everything currently set, which is
        what a fresh tracker attached to a loaded save state should report.
        """
        current = self.snapshot()
        gained = current - previous
        return tuple(m.id for m in MILESTONES if m.id in gained)

    def summary(self) -> Dict[str, Any]:
        """Scoreboard for the current state.

        ``furthest`` is the highest ladder index reached, not the most recent
        thing to happen: the ladder is the scoring axis and ``max()`` over it is
        monotone even when a player picks up an early milestone late.
        """
        current = self.snapshot()
        reached = [m for m in MILESTONES if m.id in current]
        furthest = reached[-1] if reached else None
        return {
            "count": len(reached),
            "total": len(MILESTONES),
            "furthest": furthest.id if furthest else None,
            "furthest_index": furthest.ladder_index if furthest else -1,
            "latest": [m.id for m in reached[-LATEST_LIMIT:]],
        }
