"""Static Pokemon Red game data: maps, trainers, encounters, items, species, moves.

The JSON under ``pokemon_agent/data/game/`` is generated by
``scripts/gen_gamedata.py`` from the pret/pokered decompilation; this module is
the read side. Files are loaded lazily and cached, so importing costs nothing.

Every map key is a name from ``MAP_NAMES`` in ``pokemon_agent.memory.red``, and
species/move/item names are the same strings the memory reader produces, so
what the agent reads out of RAM can be looked up here directly::

    party = reader.read_party()
    info = gamedata.species(party[0]["species"])

Each file carries the upstream commit it was generated from under the top-level
``generated_from`` key; the accessors below strip it, so callers only ever see
game data.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "game"

#: Keys that are provenance, not game data.
_META_KEYS = ("generated_from",)

_CACHE: Dict[str, Dict[str, Any]] = {}


def _load(name: str) -> Dict[str, Any]:
    if name not in _CACHE:
        path = DATA_DIR / f"{name}.json"
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except FileNotFoundError:  # pragma: no cover - only if the data is missing
            raise FileNotFoundError(
                f"{path} is missing. Run: .venv/bin/python scripts/gen_gamedata.py"
            ) from None
        _CACHE[name] = payload
    return _CACHE[name]


def _data(name: str) -> Dict[str, Any]:
    return {k: v for k, v in _load(name).items() if k not in _META_KEYS}


def generated_from(name: str = "world") -> str:
    """The pokered commit a data file was generated from."""
    return _load(name)["generated_from"]


# ===================================================================
# The world
# ===================================================================


def world() -> Dict[str, Any]:
    """Every map with a header, keyed by map name.

    Each entry has ``map_id``, ``size`` (width, height in TILES),
    ``size_blocks``, ``connections`` (direction -> map name) and ``warps``.
    A warp's ``to_map`` is null only for the handful of doors whose
    destination the game itself decides at runtime (LAST_MAP).
    """
    return _data("world")["maps"]


def map_names() -> List[str]:
    return list(world())


def trainers(map_name: Optional[str] = None):
    """Trainers placed on a map, or the whole table when called with no map."""
    table = _data("trainers")
    if map_name is None:
        return table
    return table.get(map_name, [])


def encounters(map_name: str) -> Optional[Dict[str, Any]]:
    """Wild encounter slots for a map, or None where nothing is encounterable.

    ``{"grass": {"rate": int, "slots": [...]}, "water": None}``; ``rate`` is the
    per-step encounter rate out of 256 and each slot's ``chance`` is its share
    of an encounter once one triggers.
    """
    return _data("encounters").get(map_name)


def items(map_name: str) -> List[Dict[str, Any]]:
    """Ground items and hidden items on a map, with tile coordinates."""
    return _data("items").get(map_name, [])


def shops(map_name: str) -> Optional[Dict[str, Any]]:
    """Mart inventory for a map: ``items`` plus a ``counters`` breakdown."""
    return _data("shops").get(map_name)


# ===================================================================
# Species and moves
# ===================================================================


def species(name: str) -> Optional[Dict[str, Any]]:
    return _data("species").get(name)


def all_species() -> Dict[str, Any]:
    return _data("species")


def move(name: str) -> Optional[Dict[str, Any]]:
    return _data("moves").get(name)


def all_moves() -> Dict[str, Any]:
    return _data("moves")


def types() -> Dict[str, Any]:
    """``types``, ``physical_types``, ``special_types`` and the ``chart``."""
    return _data("types")


def effectiveness(move_type: str, defender_types: Sequence[str]) -> float:
    """Type multiplier, e.g. Water on Rock/Ground is 4.0 and Normal on Ghost 0.0."""
    chart = types()["chart"].get(move_type, {})
    multiplier = 1.0
    for defender_type in defender_types:
        multiplier *= chart.get(defender_type, 1.0)
    return multiplier


# ===================================================================
# Damage
# ===================================================================


def _stat(mon: Dict[str, Any], *names: str) -> int:
    """Read a stat from either a memory-reader mon or a plain dict."""
    stats = mon.get("stats") or {}
    for name in names:
        if name in stats:
            return int(stats[name])
        if name in mon:
            return int(mon[name])
    raise KeyError(f"none of {names} in {sorted(set(mon) | set(stats))}")


def _types_of(mon: Dict[str, Any]) -> List[str]:
    if mon.get("types"):
        return list(mon["types"])
    entry = species(mon.get("species", "")) or {}
    return list(entry.get("types", []))


def damage_range(
    attacker: Dict[str, Any], move_name: str, defender: Dict[str, Any]
) -> Tuple[int, int]:
    """Gen 1 damage, as the (minimum, maximum) roll.

    Accepts the mon dicts the memory reader produces (``level``, ``types`` and
    ``stats`` with ``attack``/``defense``/``special``); flat ``atk``/``def``/
    ``spc`` keys work too.

    The Gen 1 formula, in the order the game applies it:

        damage = (2 * level / 5 + 2) * attack * power / defense / 50 + 2
        damage = damage * 3 / 2                     if the move matches a type
        damage = damage * multiplier / 10           once per defending type
        damage = damage * random / 255              random in 217..255

    Every step truncates. Gen 1 has no split defensive stats: a special move
    attacks with the user's Special and is resisted by the target's Special.
    A move with no power (status moves) and an immunity both give (0, 0).
    """
    entry = move(move_name)
    if entry is None:
        raise KeyError(f"unknown move {move_name!r}")
    power = entry["power"]
    if not power:
        return (0, 0)

    move_type = entry["type"]
    special = move_type in types()["special_types"]
    attack = _stat(attacker, "special", "spc") if special else _stat(attacker, "attack", "atk")
    defense = _stat(defender, "special", "spc") if special else _stat(defender, "defense", "def")
    level = int(attacker["level"])

    damage = ((2 * level // 5 + 2) * attack * power // defense) // 50 + 2
    if move_type in _types_of(attacker):
        damage = damage * 3 // 2
    for defender_type in _types_of(defender):
        numerator = int(effectiveness(move_type, [defender_type]) * 10)
        damage = damage * numerator // 10
    if damage <= 0:
        return (0, 0)

    return (max(1, damage * 217 // 255), damage)
